server {
    listen 80;
    server_name seudominio.com www.seudominio.com; # O domínio que o usuário digita

    # Aponta para a pasta onde você colocou os arquivos do 'npm run build'
    root /var/www/clone_twitter/frontend/dist;
    index index.html;

    location / {
        # A regra de ouro para React Router funcionar no Nginx:
        # Tenta carregar o arquivo, se não achar, redireciona para o index.html
        try_files $uri $uri/ /index.html;
    }
}