server {
    # A porta que o mundo acessa
    listen 80;
    server_name api.seudominio.com; # Ou o IP do seu servidor

    # Repassa as requisições para o Gunicorn
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve os arquivos de upload de fotos diretamente pelo Nginx (muito mais rápido)
    location /media/ {
        alias /var/www/clone_twitter/backend/media/;
    }
}